/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/Account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InFarmAdvisorRouteImport } from './routes/in/farm-advisor'
import { Route as In_layoutRouteImport } from './routes/in/__layout'
import { Route as InDashboardRouteImport } from './routes/in/Dashboard'
import { Route as ApiFarmChatRouteImport } from './routes/api/farm-chat'
import { Route as ApiConversationRouteImport } from './routes/api/conversation'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai-summary'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiSalesUpdateRouteImport } from './routes/api/sales/update'
import { Route as ApiSalesFetchRouteImport } from './routes/api/sales/fetch'
import { Route as ApiSalesDeleteRouteImport } from './routes/api/sales/delete'
import { Route as ApiSalesAddRouteImport } from './routes/api/sales/add'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const InRouteImport = createFileRoute('/in')()

const InRoute = InRouteImport.update({
  id: '/in',
  path: '/in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/Account',
  path: '/Account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InFarmAdvisorRoute = InFarmAdvisorRouteImport.update({
  id: '/farm-advisor',
  path: '/farm-advisor',
  getParentRoute: () => InRoute,
} as any)
const In_layoutRoute = In_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => InRoute,
} as any)
const InDashboardRoute = InDashboardRouteImport.update({
  id: '/in/Dashboard',
  path: '/in/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFarmChatRoute = ApiFarmChatRouteImport.update({
  id: '/api/farm-chat',
  path: '/api/farm-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationRoute = ApiConversationRouteImport.update({
  id: '/api/conversation',
  path: '/api/conversation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai-summary',
  path: '/api/ai-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesUpdateRoute = ApiSalesUpdateRouteImport.update({
  id: '/api/sales/update',
  path: '/api/sales/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesFetchRoute = ApiSalesFetchRouteImport.update({
  id: '/api/sales/fetch',
  path: '/api/sales/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesDeleteRoute = ApiSalesDeleteRouteImport.update({
  id: '/api/sales/delete',
  path: '/api/sales/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSalesAddRoute = ApiSalesAddRouteImport.update({
  id: '/api/sales/add',
  path: '/api/sales/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/api/ai-summary': typeof ApiAiSummaryRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/in/Dashboard': typeof InDashboardRoute
  '/in': typeof In_layoutRoute
  '/in/farm-advisor': typeof InFarmAdvisorRoute
  '/api/sales/add': typeof ApiSalesAddRoute
  '/api/sales/delete': typeof ApiSalesDeleteRoute
  '/api/sales/fetch': typeof ApiSalesFetchRoute
  '/api/sales/update': typeof ApiSalesUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/api/ai-summary': typeof ApiAiSummaryRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/in/Dashboard': typeof InDashboardRoute
  '/in': typeof In_layoutRoute
  '/in/farm-advisor': typeof InFarmAdvisorRoute
  '/api/sales/add': typeof ApiSalesAddRoute
  '/api/sales/delete': typeof ApiSalesDeleteRoute
  '/api/sales/fetch': typeof ApiSalesFetchRoute
  '/api/sales/update': typeof ApiSalesUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/api/ai-summary': typeof ApiAiSummaryRoute
  '/api/conversation': typeof ApiConversationRoute
  '/api/farm-chat': typeof ApiFarmChatRoute
  '/in/Dashboard': typeof InDashboardRoute
  '/in': typeof InRouteWithChildren
  '/in/__layout': typeof In_layoutRoute
  '/in/farm-advisor': typeof InFarmAdvisorRoute
  '/api/sales/add': typeof ApiSalesAddRoute
  '/api/sales/delete': typeof ApiSalesDeleteRoute
  '/api/sales/fetch': typeof ApiSalesFetchRoute
  '/api/sales/update': typeof ApiSalesUpdateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Account'
    | '/api/ai-summary'
    | '/api/conversation'
    | '/api/farm-chat'
    | '/in/Dashboard'
    | '/in'
    | '/in/farm-advisor'
    | '/api/sales/add'
    | '/api/sales/delete'
    | '/api/sales/fetch'
    | '/api/sales/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Account'
    | '/api/ai-summary'
    | '/api/conversation'
    | '/api/farm-chat'
    | '/in/Dashboard'
    | '/in'
    | '/in/farm-advisor'
    | '/api/sales/add'
    | '/api/sales/delete'
    | '/api/sales/fetch'
    | '/api/sales/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/Account'
    | '/api/ai-summary'
    | '/api/conversation'
    | '/api/farm-chat'
    | '/in/Dashboard'
    | '/in'
    | '/in/__layout'
    | '/in/farm-advisor'
    | '/api/sales/add'
    | '/api/sales/delete'
    | '/api/sales/fetch'
    | '/api/sales/update'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiConversationRoute: typeof ApiConversationRoute
  ApiFarmChatRoute: typeof ApiFarmChatRoute
  InDashboardRoute: typeof InDashboardRoute
  InRoute: typeof InRouteWithChildren
  ApiSalesAddRoute: typeof ApiSalesAddRoute
  ApiSalesDeleteRoute: typeof ApiSalesDeleteRoute
  ApiSalesFetchRoute: typeof ApiSalesFetchRoute
  ApiSalesUpdateRoute: typeof ApiSalesUpdateRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/in': {
      id: '/in'
      path: '/in'
      fullPath: '/in'
      preLoaderRoute: typeof InRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Account': {
      id: '/Account'
      path: '/Account'
      fullPath: '/Account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in/farm-advisor': {
      id: '/in/farm-advisor'
      path: '/farm-advisor'
      fullPath: '/in/farm-advisor'
      preLoaderRoute: typeof InFarmAdvisorRouteImport
      parentRoute: typeof InRoute
    }
    '/in/__layout': {
      id: '/in/__layout'
      path: '/in'
      fullPath: '/in'
      preLoaderRoute: typeof In_layoutRouteImport
      parentRoute: typeof InRoute
    }
    '/in/Dashboard': {
      id: '/in/Dashboard'
      path: '/in/Dashboard'
      fullPath: '/in/Dashboard'
      preLoaderRoute: typeof InDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/farm-chat': {
      id: '/api/farm-chat'
      path: '/api/farm-chat'
      fullPath: '/api/farm-chat'
      preLoaderRoute: typeof ApiFarmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation': {
      id: '/api/conversation'
      path: '/api/conversation'
      fullPath: '/api/conversation'
      preLoaderRoute: typeof ApiConversationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-summary': {
      id: '/api/ai-summary'
      path: '/api/ai-summary'
      fullPath: '/api/ai-summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/update': {
      id: '/api/sales/update'
      path: '/api/sales/update'
      fullPath: '/api/sales/update'
      preLoaderRoute: typeof ApiSalesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/fetch': {
      id: '/api/sales/fetch'
      path: '/api/sales/fetch'
      fullPath: '/api/sales/fetch'
      preLoaderRoute: typeof ApiSalesFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/delete': {
      id: '/api/sales/delete'
      path: '/api/sales/delete'
      fullPath: '/api/sales/delete'
      preLoaderRoute: typeof ApiSalesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sales/add': {
      id: '/api/sales/add'
      path: '/api/sales/add'
      fullPath: '/api/sales/add'
      preLoaderRoute: typeof ApiSalesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InRouteChildren {
  In_layoutRoute: typeof In_layoutRoute
  InFarmAdvisorRoute: typeof InFarmAdvisorRoute
}

const InRouteChildren: InRouteChildren = {
  In_layoutRoute: In_layoutRoute,
  InFarmAdvisorRoute: InFarmAdvisorRoute,
}

const InRouteWithChildren = InRoute._addFileChildren(InRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiConversationRoute: ApiConversationRoute,
  ApiFarmChatRoute: ApiFarmChatRoute,
  InDashboardRoute: InDashboardRoute,
  InRoute: InRouteWithChildren,
  ApiSalesAddRoute: ApiSalesAddRoute,
  ApiSalesDeleteRoute: ApiSalesDeleteRoute,
  ApiSalesFetchRoute: ApiSalesFetchRoute,
  ApiSalesUpdateRoute: ApiSalesUpdateRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
